options iwlwifi fw_restart=1
options iwlwifi led_mode=0
options iwlwifi power_save=0
options iwlwifi power_level=1
options iwlwifi disable_11ac=0
options iwlwifi disable_11ax=0
options iwlwifi disable_11be=0